create table ${schemakeeper_schema}.schema_type (
  schema_type_name varchar(255) not null,
  constraint schema_type_pk primary key (schema_type_name)
);

create table ${schemakeeper_schema}.compatibility_type (
  compatibility_type_name varchar(255) not null,
  constraint compatibility_type_pk primary key (compatibility_type_name)
);

create table ${schemakeeper_schema}.subject (
  subject_name varchar(255) not null,
  compatibility_type_name varchar(255) not null,
  is_locked boolean default false not null,
  creation_ts timestamp default current_timestamp not null,
  constraint subject_pk primary key (subject_name),
  constraint subject_compatibility_type_fk foreign key (compatibility_type_name) references ${schemakeeper_schema}.compatibility_type (compatibility_type_name)
);

create table ${schemakeeper_schema}.schema_info (
  schema_id int generated by default as identity (start with 1),
  schema_type_name varchar(255) not null,
  schema_text blob not null,
  schema_hash char(32) not null,
  creation_ts timestamp default current_timestamp not null,
  constraint schema_info_pk primary key (schema_id),
  constraint schema_type_fk foreign key (schema_type_name) references ${schemakeeper_schema}.schema_type (schema_type_name),
  constraint schema_info_schema_hash_unique unique (schema_hash)
);

create table ${schemakeeper_schema}.subject_schema (
  subject_name varchar(255) not null,
  schema_id int not null,
  version int not null,
  creation_ts timestamp default current_timestamp not null,
  constraint subject_schema_pk primary key (subject_name, schema_id),
  constraint subject_schema_version_unique unique (subject_name, version),
  constraint subject_fk foreign key (subject_name) references ${schemakeeper_schema}.subject (subject_name),
  constraint schema_fk foreign key (schema_id) references ${schemakeeper_schema}.schema_info (schema_id)
);

insert into ${schemakeeper_schema}.schema_type(schema_type_name) values ('avro');
insert into ${schemakeeper_schema}.schema_type(schema_type_name) values ('thrift');
insert into ${schemakeeper_schema}.schema_type(schema_type_name) values ('protobuf');

insert into ${schemakeeper_schema}.compatibility_type(compatibility_type_name) values ('none');
insert into ${schemakeeper_schema}.compatibility_type(compatibility_type_name) values ('backward');
insert into ${schemakeeper_schema}.compatibility_type(compatibility_type_name) values ('forward');
insert into ${schemakeeper_schema}.compatibility_type(compatibility_type_name) values ('full');
insert into ${schemakeeper_schema}.compatibility_type(compatibility_type_name) values ('backward_transitive');
insert into ${schemakeeper_schema}.compatibility_type(compatibility_type_name) values ('forward_transitive');
insert into ${schemakeeper_schema}.compatibility_type(compatibility_type_name) values ('full_transitive');
