pull_request_rules:
  - name: assign and label scala-steward's PRs
    conditions:
      - author=scala-steward
    actions:
      label:
        add: [dependency-update]
  - name: automatically merge Scala Steward PRs on CI success
    conditions:
      - author=scala-steward
      - "status-success=Scala 2.12.13, Java adopt@1.8"
    actions:
      merge:
        method: merge