language: scala

jdk:
- openjdk8

services:
- docker

before_install:
- docker pull schemakeeper/server:0.1
- docker pull postgres:9.6
- docker pull mysql:5.7
- docker pull quay.io/testcontainers/ryuk:0.2.3
- sudo apt-get update -qq
- sudo apt-get install automake bison flex g++ git libboost-all-dev libevent-dev libssl-dev libtool make pkg-config
- wget http://www.us.apache.org/dist/thrift/0.12.0/thrift-0.12.0.tar.gz
- tar xfz thrift-0.12.0.tar.gz
- cd thrift-0.12.0 && ./bootstrap.sh && ./configure --help && ./configure --with-qt5=NO --with-c_glib=NO --with-openssl=NO=DIR --with-csharp=NO --with-erlang=NO --with-nodejs=NO --with-nodets=NO --with-lua=NO --with-python=NO --with-py3=NO --with-perl=NO --with-php=NO --with-php_extension=NO --with-dart=NO --with-ruby=NO --with-haskell=NO --with-go=NO --with-swift=NO --with-rs=NO --with-cl=NO --with-haxe=NO --with-dotnetcore=NO --with-d=NO && sudo make && sudo make install
- cd ./..
- sudo apt-get install autoconf curl unzip
- wget https://github.com/protocolbuffers/protobuf/releases/download/v3.7.1/protobuf-java-3.7.1.tar.gz
- tar xfz protobuf-java-3.7.1.tar.gz
- cd protobuf-java-3.7.1.tar.gz && ./configure && sudo make install && sudo ldconfig
- cd ./..

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

install:
  - ./gradlew assemble

script:
  - ./gradlew build
