language: scala

jdk:
- openjdk8

dist: trusty

services:
- docker

before_install:
- docker pull schemakeeper/server:0.1
- docker pull postgres:9.6
- docker pull mysql:5.7
- docker pull quay.io/testcontainers/ryuk:0.2.3
- docker pull gradle:jdk8-alpine
- docker pull openjdk:8-jre-alpine
- sudo apt-get install thrift-compiler
- sudo apt-get install -y autoconf automake libtool curl make g++ unzip
- wget https://github.com/protocolbuffers/protobuf/releases/download/v3.7.1/protobuf-java-3.7.1.tar.gz
- ls -l
- tar xfz protobuf-java-3.7.1.tar.gz
- ls -l
- cd protobuf-3.7.1 && ./configure && sudo make install && sudo ldconfig
- cd ./..

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

before_script:
  - chmod +x gradlew

install:
  - docker build -t schemakeeper/server:test .
  - ./gradlew assemble

script:
  - ./gradlew check
  - ./gradlew codeCoverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false

branches:
  only:
  - master
