name: Docker image publish
on:
  push:
    branches: [master, main]
    tags: ["v*"]
  pull_request:
    branches: [master, main] # for testing
jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4

      - uses: olegtarasov/get-tag@v2.1
        id: tagName
#        with:
#          tagRegex: "v(.*)"

      - name: Set tag
        run: echo "DOCKER_TAG=$GIT_TAG_NAME"

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Java and Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.8

      - name: Print docker tag
        run: echo $DOCKER_TAG

#      - name: Publish docker image
#        run: sbt ++${{ matrix.scala }} server/docker:publish
