name: Docker image publish
on:
  push:
    branches: [master, main]
    tags: ["*"]
  pull_request:
    branches: [master, main] # for testing
jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Docker meta
        uses: docker/metadata-action@v3
        id: meta
        with:
          images: nryanov/schemakeeper

#      - name: Login to DockerHub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Print
        run: echo ${{ steps.meta.outputs.tags }} && echo ${{ steps.meta.outputs.labels }}

#      - name: Set up Java and Scala
#        uses: olafurpg/setup-scala@v10
#        with:
#          java-version: ${{ matrix.java }}
#
#      - name: Prepare local schemakeeper image
#        run: sbt ++${{ matrix.scala }} server/docker:publishLocal